- name: Add traefik helm chart repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Deploy traefik ingress controller
  kubernetes.core.helm:
    chart_ref: traefik/traefik
    create_namespace: yes
    update_repo_cache: yes
    name: traefik
    release_namespace: default
    wait: true
    values:
      ingressRoute:
        dashboard:
          enabled: true
      service:
        type: LoadBalancer
      externalIPs:
        - "{{ ingress_external_ip }}"

- name: Add cert manager helm chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert manager chart
  kubernetes.core.helm:
    chart_ref: jetstack/cert-manager
    update_repo_cache: yes
    name: cert-manager
    release_namespace: "{{ harbor_namespace }}"
    values:
      installCRDs: true
