- hosts: localhost # Kubectl is configured from this machine
  roles:
    - deploy_dev_db
    - deploy_harbor
  vars:
    # Helm chart versions
    # https://github.com/goharbor/harbor/releases
    harbor_version: "1.10.17"

    # K8s namespace
    harbor_namespace: harbor

    # Helm name of the service
    harbor_deployed_name: harbor

    # Database name and IP
    db_host_name:
    db_user_name: postgres
