- name: ensure python3 is installed
  become: yes
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:


- name: Create Longhorn namespace
  kubernetes.core.k8s:
    name: longhorn-system
    kind: Namespace
    state: present

- name: Download Longhorn repo
  ansible.builtin.git:
    repo: "https://github.com/longhorn/longhorn.git"
    dest: "/tmp/longhorn"
    
    update: true # Automatically pull bug-fixes in

- name: Install Longhorn prerequisites
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}" 
    namespace: longhorn-system
  with_items:
    - "/tmp/longhorn/deploy/prerequisite/longhorn-iscsi-installation.yaml"
    - "/tmp/longhorn/deploy/prerequisite/longhorn-nfs-installation.yaml"

- name: Install Longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    
    repo_url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    name: longhorn
    chart_version: "{{ longhorn_version }}"
    release_namespace: longhorn-system
    update_repo_cache: yes
    release_values:
      service:
        ui:
          type: LoadBalancer
      persistence:
        defaultClassReplicaCount: 3
        defaultDataLocality: disabled

- name: Create a new databases 
  postgresql_db:
    name: "{{ item }}"
    state: present
    login_host: "{{ db_host_name }}"
    login_user: "{{ db_user_name }}"
    login_password: "{{ lookup('env', 'DB_PASSWORD') }}"
  with_items: 
    - "registry"
    - "notary_signer"
    - "notary_server"